# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlichungs-Datum')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('publish', 'Veröffentlicht'), ('trash', 'Gelöscht')], max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
