# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160728_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Inhalt'),
        ),
    ]
